import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';
import './globals.css';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "淹水防治",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html lang="zh-TW">
      <body className="pt-20"> {/* 預留 Navbar 高度 */}
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
